### ISSUE TITLE
libxmlSimu not found when upgrading XMPPFramework to 3.6.6 via cocoapods

### ISSUE THREAD

**Issue by d4r1091** [robbiehanson/XMPPFramework#591] opened 2015-09-09 12:46 UTC
I guys I found this issue when upgrading to the latest version of XMPPFramework.
ClassName: DDXMLNode.h
Module: KissXML

```objective-c
#if !(TARGET_IPHONE_SIMULATOR)
@import libxml;
#else
@import libxmlSimu;
#endif
```

Compiler mark line 4 with an error explaining: 
Module 'libxmlSimu' not found.

How can I solve this issue?
Thanks a lot,
Dario

**Comment by max-potapov** [comment] 2015-09-11 08:07
XMPPFramework podspec is pointing to ProcessOne's fork.

- They have typo in libxmlSimu module definition. Correct path for header is:
```js
"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2/libxml/tree.h"
```

- You need to forward modules in your framework pod like:
```ruby
s.xcconfig = {
  'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(SDKROOT)/usr/include/libresolv $(PODS_ROOT)/XMPPFramework/module',
  'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  'OTHER_LDFLAGS' => '"$(inherited)" "-lxml2" "-objc"'
}
```

**Comment by d4r1091** [comment] 2015-09-11 08:27
thanks @max-potapov !
do you have some podspec with all the dependecies fixed? thanks a lot

**Comment by max-potapov** [comment] 2015-09-11 08:50
I've this one (based on ProcessOne spec): https://github.com/unisontech/PodSpecs/blob/master/uXMPPFramework/3.6.6/uXMPPFramework.podspec
but it's under WIP

**Comment by d4r1091** [comment] 2015-09-11 09:07
thanks a million! @max-potapov I'll try ;)

**Comment by chrisballinger** [comment] 2015-09-15 21:25
We will now be maintaining an official XMPPFramework podspec thanks to the great work by the processOne team in PR #595.

**Comment by 7357011** [comment] 2015-09-17 01:10
I wonder how to  forward modules in my framework pod, I am a learner , could you help me please?
============================
s.xcconfig = {
  'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(SDKROOT)/usr/include/libresolv $(PODS_ROOT)/XMPPFramework/module',
  'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  'OTHER_LDFLAGS' => '"$(inherited)" "-lxml2" "-objc"'
}

**Comment by Shrutimittal91** [comment] 2015-09-24 11:57
I am getting the same error 
libxml not found
libxmlsimu not found

i tried adding this also
"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2/libxml/tree.h"

but still i am getting the error. Please help.

**Comment by chrisballinger** [comment] 2015-09-24 17:06
Working on it...

**Comment by Shrutimittal91** [comment] 2015-09-25 06:18
Thanks for the immediate response. Please let me know how much time it will
take. I need to integrate it in my project.

On Thu, Sep 24, 2015 at 10:36 PM, Chris Ballinger <notifications@github.com>
wrote:

> Working on it...
>
> On Thu, Sep 24, 2015 at 4:57 AM, Shrutimittal91 <notifications@github.com>
> wrote:
>
> > I am getting the same error
> > libxml not found
> > libxmlsimu not found
> >
> > i tried adding this also
> >
> >
> "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2/libxml/tree.h"
> >
> > but still i am getting the error. Please help.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-142908215
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-142990744>
> .
>



-- 
Thanks & Regards
Shruti Mittal

**Comment by haduyenhoa** [comment] 2015-10-06 20:07
Verify if your XCode application is in /Applications folder but not else where. If it's not the case, change the path define the libxmlSimu to the right path. Normaly, the definition of libxmlSimu is in the file: "module.modulemap" in KissXML project of your pod. 

It's just a temporal solution.

**Comment by Shrutimittal91** [comment] 2015-10-07 06:41
@haduyenhoa  My xcode is in applications only.
And the path defined for libxmlsimu in "module.modulemap" is 
"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libxml2/libxml/tree.h"

**Comment by haduyenhoa** [comment] 2015-10-07 08:08
Verify if you have tree.h in that path. Otherwise, replace that path by "/usr/include/libxml2/libxml/tree.h" (be sure that you have tree.h at the path that you give to module.modulemap)

**Comment by userException** [comment] 2015-10-08 09:50
I am still getting this error.. Although I have not used PODS... If followed this post http://stackoverflow.com/questions/9091767/up-to-date-instructions-on-how-to-install-xmppframework-manually/30543948#30543948 for installation steps

**Comment by purrrminator** [comment] 2015-10-17 13:58
Just downloaded the entire framework, can't run iPhone sample app because of this issue.

**Comment by purrrminator** [comment] 2015-10-17 14:23
but then... same issue with dnssd/dnssdSim
```
#if !(TARGET_IPHONE_SIMULATOR)
@import dnssd;
#else
@import dnssdSimu;
#endif
```

**Comment by AbeiOS** [comment] 2015-10-21 03:30
@max-potapov  thanks for your answer  to fix this issue 
#if !(TARGET_IPHONE_SIMULATOR)
@import dnssd;
#else
@import dnssdSimu;
#endif  
but i attemp to try solve this problem use this way ，it is not work  - - ！
could you have some detail steps to fixs this problem~~~ please ！

**Comment by max-potapov** [comment] 2015-10-21 07:21
module map definitions should work with this option enabled:
![screen shot 2015-10-21 at 10 20 34](https://cloud.githubusercontent.com/assets/1907011/10630110/2a999146-77dd-11e5-8d00-51c4cc2d2c71.png)

**Comment by AbeiOS** [comment] 2015-10-21 07:25
i will try it soon

**Comment by AbeiOS** [comment] 2015-10-21 07:29
@max-potapov it's worked ! thanks   max-potapov

**Comment by AbeiOS** [comment] 2015-10-21 07:34
Bother you again ，😢 。。。。
![2015-10-21 3 33 11](https://cloud.githubusercontent.com/assets/12441461/10630471/3c8017f0-7809-11e5-9c74-89b03ecbcf1c.png)

**Comment by max-potapov** [comment] 2015-10-21 08:35
@AbeiOS could you try example from PR?
1. run pod install
2. open iPhoneXMPP.xcworkspace

**Comment by AbeiOS** [comment] 2015-10-21 08:38
i don't use the pod ,must me to install pod?

**Comment by Shrutimittal91** [comment] 2015-10-21 08:58
I also face the same problem, After trying all the possible solution I used
pods.
I deleted the XMPP files from my project and added this line in my podfile:

pod 'XMPPFramework', :podspec => '
https://raw.githubusercontent.com/andrey-justo-movile/XMPPFramework/3.7.2/XMPPFramework.podspec.json
'

And everything worked fine after thats.

On Wed, Oct 21, 2015 at 2:08 PM, AbeiOS <notifications@github.com> wrote:

> i don't use the pod ,must me to install pod?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-149819515>
> .
>



-- 
Thanks & Regards
Shruti Mittal

**Comment by AbeiOS** [comment] 2015-10-21 08:59
@Shrutimittal91 that's right thanks you~i will try it

**Comment by purrrminator** [comment] 2015-10-21 09:02
@AbeiOS read my posts above

**Comment by AbeiOS** [comment] 2015-10-21 09:04
@purrrminator  all right ~ i want to know what is PR ？I am a green hand

**Comment by AbeiOS** [comment] 2015-10-21 09:07
@purrrminator thank you ！this problem is solved 。

**Comment by derbshireram** [comment] 2015-10-30 07:26
Is there a fix for this without using CocoaPods? It was working fine before the changes to support CocoaPods.

**Comment by AbeiOS** [comment] 2015-10-30 07:38
i don't know ，why not use the CocoaPods?

**Comment by derbshireram** [comment] 2015-10-30 07:49
@AbeiOS because CocoaPods is very heavyweight while I prefer Carthage. There's no reason why CocoaPods should be made a requirement especially since it was working fine before!

**Comment by itolisto** [comment] 2015-11-05 01:50
Still not working for me ):

**Comment by fltx** [comment] 2015-11-14 14:29
@purrrminator   Thank you very much,according your method I did it succeeded!

**Comment by devshubh** [comment] 2015-11-18 09:49
Can't resolve this issue. Still no Success. No proper guide available.
Can we use XMPPFramework without pod. If possible than how to add module. Please provide step by step guide to configure XMPPFramework in Xcode project because using previous guide it isn't working.

**Comment by purrrminator** [comment] 2015-11-18 09:50
@devshubh did you try my solution?

**Comment by purrrminator** [comment] 2015-11-18 09:58
My own experience:
1. The issue happens if the library was used without pods.
2. The issue happens if the pod was installed with `use_frameworks!` directive.

**Comment by raviasmile4u** [comment] 2015-12-02 12:16
I tried everything but the issue is not resolved. I am using Xcode 7. Please help me to resolve this asap.

**Comment by purrrminator** [comment] 2015-12-02 12:18
@raviasmile4u does your podfile contains `use_frameworks!` ?

**Comment by raviasmile4u** [comment] 2015-12-02 12:19
@purrrminator how can i check this ???

**Comment by purrrminator** [comment] 2015-12-02 12:20
@raviasmile4u do you use cocoapods? if not, try this (https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-148917613 + https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-148918795)

**Comment by raviasmile4u** [comment] 2015-12-02 12:23
@purrrminator  yes I use cocoapods

**Comment by purrrminator** [comment] 2015-12-02 12:24
@raviasmile4u then why do you ask me about podfile. This file is essential for any cocoapods user.

**Comment by raviasmile4u** [comment] 2015-12-02 12:25
@purrrminator I dont know much about that

**Comment by purrrminator** [comment] 2015-12-02 12:26
@raviasmile4u please come back when you do

**Comment by raviasmile4u** [comment] 2015-12-02 13:14
@purrrminator  I checked, podfile does not contain use_frameworks

**Comment by purrrminator** [comment] 2015-12-02 13:15
@raviasmile4u try this (https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-148917613 + https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-148918795)

**Comment by raviasmile4u** [comment] 2015-12-02 13:19
tried.....but again it is throwing error

**Comment by purrrminator** [comment] 2015-12-02 13:26
@raviasmile4u If you want get some help, give more details. What error? Also try this in terminal `find /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs -name tree.h`

**Comment by raviasmile4u** [comment] 2015-12-02 13:28
![screen shot 2015-12-02 at 6 57 12 pm](https://cloud.githubusercontent.com/assets/16117527/11531959/9803a0ae-9926-11e5-9649-92d1122c0822.png)

**Comment by purrrminator** [comment] 2015-12-02 13:29
@raviasmile4u do you see what I see? As I wrote previously you have to change `@import libxml;` to `#import "libxml/tree.h"` like this:
```
#if !(TARGET_IPHONE_SIMULATOR)
#import "libxml/tree.h"
#else
#import "libxml/tree.h"
#endif
```

**Comment by raviasmile4u** [comment] 2015-12-02 13:32
Thanks, that error gone but now another error..ld: 180 duplicate symbols for architecture x86_64

**Comment by purrrminator** [comment] 2015-12-02 13:36
@raviasmile4u this error may be caused by many reasons, better google it and find the solution for you particular case

**Comment by raviasmile4u** [comment] 2015-12-02 13:37
@purrrminator ok i will search it and resolve it ...thanx

**Comment by raviasmile4u** [comment] 2015-12-03 08:53
ld: library not found for -lidn
clang: error: linker command failed with exit code 1 (use -v to see invocation)

getting this error....can anyone help me ???

**Comment by devshubh** [comment] 2016-01-10 07:19
There is a fix by using $(PROJECT_DIR)/modules/modulamap. this header would help to locate new ".modulemap " file which detects the "libsimu" file. locate the file properly and this issue would be resolved. Feel free to ask more.

**Comment by jschmid** [comment] 2016-01-11 15:40
@derbshireram you mentioned Carthage in your comment above: https://github.com/robbiehanson/XMPPFramework/issues/591#issuecomment-152452567.

Have you succeeded in using Carthage to build XMPPFramework ? I do have trouble setting up a framework project for it. (Which seems to be related to this issue as well)

**Comment by muzammal-PowerfulPal** [comment] 2016-01-21 12:56
Solved My Problem:
http://stackoverflow.com/questions/33595234/xmppframework-could-not-build-module-libxml

**Comment by marro37** [comment] 2016-08-11 18:12
I had this issue when I created my own pod with XMPPFramework as dependency (before that everything was working fine). What I did was add the following line on my podspec.json:
"HEADER_SEARCH_PATHS": "$(inherited) $(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/XMPPFramework/module $(SDKROOT)/usr/include/libresolv" 

Feel free to ask more

**Comment by rgkobashi** [comment] 2016-08-11 18:13
I had this issue when I created my own pod with XMPPFramework as dependency (before that everything was working fine). What I did was add the following line on my podspec.json:
"HEADER_SEARCH_PATHS": "$(inherited) $(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/XMPPFramework/module $(SDKROOT)/usr/include/libresolv" 

Feel free to ask more

**Comment by chrisballinger** [comment] 2016-08-11 18:34
You realize that this is no longer needed right? Point your podspec at the master branch and it no longer needs the modules.

**Comment by rgkobashi** [comment] 2016-08-11 18:48
As far as I know I couldn't specify the source of one of my dependencies. I did a little research about that and I understood that is not possible. Currently I am downloading all my dependencies from https://github.com/CocoaPods/Specs.git
Probably I am missing something...

**Comment by chrisballinger** [comment] 2016-08-11 19:34
```ruby
pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
```

**Closed by chrisballinger** 2016-08-11 19:34 UTC

**Comment by ashevin** [comment] 2016-08-28 03:45
@rgkobashi 

I am having the same trouble with including XMPPFramework as a dependency in a private Pod.  Could you provide more details on where those lines should be added?

**Comment by rgkobashi** [comment] 2016-08-28 08:26
I didn't specified the source of the pod, that solution didn't work for me. What I did was, keep value for HEADER_SEARCH_PATHS on my private podspec.json and it works with no issues. Feel free to ask more...
